spring:
    ai:
      openai:
        api-key: ${OPENAI_API_KEY}
    datasource:
        url: jdbc:postgresql://localhost:5435/postgres
        username: postgres
        password: postgres
   
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8081